</div> <!-- end of content -->
<div id="clear_fix">
</div>
<div id="footer_box">
	<div id="info_foot_box">
		<div class="church_left">
		<img src="images/umcCross.png" alt="cross" align="left" style="margin-right:10px;" />
			Sponsored by:<br />
			<a class="foot_link" href="http://bensonmemorial.org/">Benson Memorial United Methodist Church</a><br />
			4706 Creedmoor Road<br />
			Raleigh, North Carolina 27612<br />
		</div>
		<div class="contact_right">
		<img src="images/scoutlogo.png" alt="cross" align="right" style="margin-left:10px;" />
			Contact the <a class="foot_link" href="mailto:scoutmaster@troop-214.org">Scoutmaster</a> or the <a class="foot_link" href="mailto:spl@troop-214.org">Senior Patrol Leader.</a><br />
			Contact the <a class="foot_link" href="mailto:webmaster@troop-214.org?subject=BSA%20Site%20Issue">Webmaster</a> about site problems.<br />
			Logos & Artwork © 2012 - BSA and T-214<br />
		</div>
	</div>

	<div class="login_webmaster">
		Webmaster's Login: <a class"foot_link" href="webmaster/">Here</a>
	</div>
</div>


</body>
</html>