<div class="nav">
	<ul>
		<li><a class="nav_items" href="<?php echo full_link('index.php'); ?>">Home</a></li>
		<li><a class="nav_items" href="<?php echo full_link('about.php'); ?>">About Us</a></li>
		<li><a class="nav_items" href="<?php echo full_link('link.php'); ?>">Links</a></li>
		<li><a class="nav_items" href="<?php echo full_link('index.php'); ?>">Photos</a></li>
		<li><a class="nav_items" href="<?php echo full_link('eaglelist.php'); ?>">Eagles</a></li>
		<li><a class="nav_items" href="<?php echo full_link('doc.php'); ?>">Documents</a></li>
	</ul>
</div>
<div id="content">